name: example
description: GetWidget Demo app

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^8.0.1 
  uuid: ^3.0.4
  shared_preferences: ^2.0.8
  getwidget:
    path: ../
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.2  
  sqflite: ^2.2.6
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/